services:
  mh_icecat.fetcher:
    class: haringsrob\Icecat\Model\Fetcher
    arguments:
      - '%icecat.username%'
      - '%icecat.password%'
      - ''
      - '%icecat.language%'
  mh_icecat.result:
    class: haringsrob\Icecat\Model\Result