services:
  mh_icecat.fetcher:
    class: haringsrob\Icecat\Model\Fetcher
    arguments:
      - '%icecat_username%'
      - '%icecat_password%'
      - ''
      - '%icecat_language%'
  mh_icecat.result:
    class: haringsrob\Icecat\Model\Result